import { pgTable, uuid, text, jsonb, timestamp, pgEnum } from 'drizzle-orm/pg-core';

// Type enum for content records (snapshot or update)
export const contentTypeEnum = pgEnum('content_type', ['snapshot', 'update']);

// Main document registry (like IPNS)
export const docs = pgTable('docs', {
    // Public key (similar to hypercore's public key)
    pubKey: text('pub_key').primaryKey(),

    // Latest snapshot CID
    snapshotCid: text('snapshot_cid').notNull(),

    // Array of update CIDs (as native PostgreSQL array)
    updateCids: text('update_cids').array().default([]),

    // Access control - owner's user ID
    ownerId: uuid('owner_id').notNull(),

    // Document metadata
    title: text('title').notNull(),
    description: text('description'),

    // Timestamps
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow()
});

// Content blocks (like IPFS immutable content)
export const content = pgTable('content', {
    // Content identifier (generated by hash-service)
    cid: text('cid').primaryKey(),

    // Type of content (snapshot or update)
    type: contentTypeEnum('type').notNull(),

    // Binary content (loro-doc export)
    data: jsonb('data').notNull(),

    // Timestamp when this content was created
    createdAt: timestamp('created_at').notNull().defaultNow()
});

// Types for type safety
export type Doc = typeof docs.$inferSelect;
export type InsertDoc = typeof docs.$inferInsert;

export type Content = typeof content.$inferSelect;
export type InsertContent = typeof content.$inferInsert; 